"""Add email_verification_expires

Revision ID: 16dd5c96c8e6
Revises: 001_initial
Create Date: 2026-07-25 09:07:25.865122+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16dd5c96c8e6'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('scan_mode', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('executive_summary', sa.JSON(), nullable=True))
    op.add_column('scans', sa.Column('scan_mode', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('scans', 'scan_mode')
    op.drop_column('reports', 'executive_summary')
    op.drop_column('reports', 'scan_mode')
    # ### end Alembic commands ###
