"""add_hybrid_assessment_fields

Revision ID: 24e193c914f1
Revises: 0001_initial_schema
Create Date: 2026-09-07 12:43:09.235856+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e193c914f1'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('owasp_summary', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('discovered_endpoints', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('component_inventory', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'component_inventory')
    op.drop_column('reports', 'discovered_endpoints')
    op.drop_column('reports', 'owasp_summary')
    # ### end Alembic commands ###
