"""drop_removed_features

Revision ID: 7340c9ab6be5
Revises: 24e193c914f1
Create Date: 2026-09-11 11:30:35.037443+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7340c9ab6be5'
down_revision: Union[str, None] = '24e193c914f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop child tables before parent tables to respect foreign keys
    op.drop_index(op.f('ix_asset_change_events_asset_id'), table_name='asset_change_events')
    op.drop_table('asset_change_events')

    op.drop_index(op.f('ix_assets_domain'), table_name='assets')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_table('assets')

    op.drop_index(op.f('ix_remediation_audit_logs_remediation_id'), table_name='remediation_audit_logs')
    op.drop_table('remediation_audit_logs')

    op.drop_index(op.f('ix_remediation_records_finding_id'), table_name='remediation_records')
    op.drop_index(op.f('ix_remediation_records_status'), table_name='remediation_records')
    op.drop_index(op.f('ix_remediation_records_user_id'), table_name='remediation_records')
    op.drop_table('remediation_records')

    op.drop_index(op.f('ix_project_connections_domain'), table_name='project_connections')
    op.drop_index(op.f('ix_project_connections_user_id'), table_name='project_connections')
    op.drop_table('project_connections')

    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')

    op.drop_index(op.f('ix_share_links_report_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_table('share_links')

    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('scan_preferences')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scan_preferences', sa.JSON(), nullable=True))
    op.create_table('share_links',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('report_id', sa.CHAR(length=32), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=1)
    op.create_index(op.f('ix_share_links_report_id'), 'share_links', ['report_id'], unique=False)
    op.create_table('remediation_records',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('finding_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('project_connection_id', sa.CHAR(length=32), nullable=False),
    sa.Column('vulnerability_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('detector_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=19), nullable=False),
    sa.Column('remediation_description', sa.TEXT(), nullable=True),
    sa.Column('affected_component', sa.VARCHAR(length=255), nullable=True),
    sa.Column('proposed_change', sqlite.JSON(), nullable=True),
    sa.Column('backup_data', sqlite.JSON(), nullable=True),
    sa.Column('verification_method', sa.VARCHAR(length=255), nullable=True),
    sa.Column('verification_result', sqlite.JSON(), nullable=True),
    sa.Column('verification_scan_id', sa.CHAR(length=32), nullable=True),
    sa.Column('audit_context', sqlite.JSON(), nullable=True),
    sa.Column('applied_at', sa.DATETIME(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('rolled_back_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_connection_id'], ['project_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_records_user_id'), 'remediation_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_remediation_records_status'), 'remediation_records', ['status'], unique=False)
    op.create_index(op.f('ix_remediation_records_finding_id'), 'remediation_records', ['finding_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=512), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=1)
    op.create_table('asset_change_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('asset_id', sa.CHAR(length=32), nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_change_events_asset_id'), 'asset_change_events', ['asset_id'], unique=False)
    op.create_table('remediation_audit_logs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('remediation_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('previous_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_audit_logs_remediation_id'), 'remediation_audit_logs', ['remediation_id'], unique=False)
    op.create_table('project_connections',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('connection_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_connections_user_id'), 'project_connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_connections_domain'), 'project_connections', ['domain'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=False),
    sa.Column('canonical_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('verification_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('current_score', sa.INTEGER(), nullable=False),
    sa.Column('current_grade', sa.VARCHAR(length=10), nullable=False),
    sa.Column('current_risk_level', sa.VARCHAR(length=50), nullable=False),
    sa.Column('open_critical_count', sa.INTEGER(), nullable=False),
    sa.Column('open_high_count', sa.INTEGER(), nullable=False),
    sa.Column('open_medium_count', sa.INTEGER(), nullable=False),
    sa.Column('open_low_count', sa.INTEGER(), nullable=False),
    sa.Column('last_scanned_at', sa.DATETIME(), nullable=True),
    sa.Column('tech_summary', sqlite.JSON(), nullable=True),
    sa.Column('tls_summary', sqlite.JSON(), nullable=True),
    sa.Column('dns_summary', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_index(op.f('ix_assets_domain'), 'assets', ['domain'], unique=False)
    # ### end Alembic commands ###
